name: my_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  animate_do: ^3.3.4
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

